"""Patient Health Passport — a portable, signed health summary.

Generates a structured document containing a patient's complete health
profile that they can present to any provider, on or off the Aquifer
network. The passport is:

- Patient-controlled: only generated at patient request with valid share key
- Complete: demographics, medications, allergies, conditions, insurance
- Signed: HMAC-SHA256 signature proves it was generated by an Aquifer server
- Timestamped: clear generation date so providers know how fresh it is
- Export formats: JSON (machine-readable), text (human-readable), HTML (printable)

This is the "offline" mode of Aquifer — when a patient goes to a
practice that isn't on the network, they can hand over a passport
instead.
"""

from __future__ import annotations

import hashlib
import hmac
import json
from datetime import datetime, timezone
from typing import Optional


def generate_passport(
    patient_id: str,
    patient_email: str,
    share_key: str,
    patient_data: dict[str, str],
    health_records: list[dict],
    signing_key: str,
) -> dict:
    """Generate a Health Passport for a patient.

    Args:
        patient_id: Aquifer patient ID.
        patient_email: Patient's email (masked in output).
        share_key: Patient's share key (included for verification).
        patient_data: Flat dict from get_patient_data_summary().
        health_records: List from get_health_records(decrypt=True).
        signing_key: Server signing key for HMAC signature.

    Returns:
        Passport dict with data, metadata, and signature.
    """
    generated_at = datetime.now(timezone.utc).isoformat()

    # Mask email
    at = patient_email.index("@") if "@" in patient_email else len(patient_email)
    email_masked = patient_email[:2] + ("*" * (at - 2)) + patient_email[at:]

    # Organize health records by domain
    domains = {}
    for record in health_records:
        domain = record.get("domain", "other")
        if domain not in domains:
            domains[domain] = []
        domains[domain].append({
            "type": record.get("field_type", ""),
            "label": record.get("label", ""),
            "value": record.get("value", ""),
            "date": record.get("recorded_date") or record.get("date"),
            "source": record.get("source_system", record.get("source", "")),
        })

    passport = {
        "aquifer_health_passport": {
            "version": "1.0",
            "generated_at": generated_at,
            "patient": {
                "id": patient_id,
                "email_masked": email_masked,
                "share_key": share_key,
            },
            "demographics": _extract_demographics(patient_data),
            "insurance": _extract_insurance(patient_data),
            "medications": domains.get("medications", []),
            "allergies": domains.get("allergies", []),
            "conditions": domains.get("medical_history", []),
            "dental": domains.get("dental", []),
            "surgical": domains.get("surgical", []),
            "immunizations": [
                r for r in domains.get("medical_history", [])
                if r.get("type") == "immunization"
            ],
            "vitals": [
                r for r in domains.get("medical_history", [])
                if r.get("type") in ("vital", "observation")
            ],
        },
    }

    # Remove immunizations and vitals from conditions to avoid duplication
    passport["aquifer_health_passport"]["conditions"] = [
        r for r in passport["aquifer_health_passport"]["conditions"]
        if r.get("type") not in ("immunization", "vital", "observation")
    ]

    # Sign the passport
    payload = json.dumps(passport["aquifer_health_passport"], sort_keys=True)
    signature = hmac.new(
        signing_key.encode(), payload.encode(), hashlib.sha256
    ).hexdigest()

    passport["signature"] = signature
    passport["verification"] = {
        "method": "HMAC-SHA256",
        "message": "This passport was generated by an Aquifer server. "
                   "Verify at aquifer.health/verify or contact the issuing practice.",
    }

    return passport


def passport_to_text(passport: dict) -> str:
    """Convert a Health Passport to a human-readable text format."""
    data = passport["aquifer_health_passport"]
    lines = []

    lines.append("=" * 60)
    lines.append("  AQUIFER HEALTH PASSPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"Generated: {data['generated_at']}")
    lines.append(f"Share Key: {data['patient']['share_key']}")
    lines.append("")

    # Demographics
    demo = data.get("demographics", {})
    if demo:
        lines.append("PATIENT INFORMATION")
        lines.append("-" * 40)
        for key, value in demo.items():
            lines.append(f"  {key}: {value}")
        lines.append("")

    # Insurance
    insurance = data.get("insurance", {})
    if insurance:
        lines.append("INSURANCE")
        lines.append("-" * 40)
        for key, value in insurance.items():
            lines.append(f"  {key}: {value}")
        lines.append("")

    # Medications
    meds = data.get("medications", [])
    if meds:
        lines.append("CURRENT MEDICATIONS")
        lines.append("-" * 40)
        for m in meds:
            lines.append(f"  - {m.get('label', m.get('value', ''))}")
        lines.append("")

    # Allergies
    allergies = data.get("allergies", [])
    if allergies:
        lines.append("ALLERGIES")
        lines.append("-" * 40)
        for a in allergies:
            lines.append(f"  - {a.get('label', a.get('value', ''))}")
        lines.append("")

    # Conditions
    conditions = data.get("conditions", [])
    if conditions:
        lines.append("MEDICAL HISTORY")
        lines.append("-" * 40)
        for c in conditions:
            date = f" ({c['date']})" if c.get("date") else ""
            lines.append(f"  - {c.get('label', c.get('value', ''))}{date}")
        lines.append("")

    # Dental
    dental = data.get("dental", [])
    if dental:
        lines.append("DENTAL HISTORY")
        lines.append("-" * 40)
        for d in dental:
            lines.append(f"  - {d.get('label', d.get('value', ''))}")
        lines.append("")

    # Vitals
    vitals = data.get("vitals", [])
    if vitals:
        lines.append("RECENT VITALS")
        lines.append("-" * 40)
        for v in vitals:
            date = f" ({v['date']})" if v.get("date") else ""
            lines.append(f"  - {v.get('label', '')}: {v.get('value', '')}{date}")
        lines.append("")

    lines.append("=" * 60)
    lines.append("  Verified by Aquifer | aquifer.health")
    lines.append(f"  Signature: {passport['signature'][:16]}...")
    lines.append("=" * 60)

    return "\n".join(lines)


def passport_to_html(passport: dict) -> str:
    """Convert a Health Passport to a printable HTML document."""
    data = passport["aquifer_health_passport"]
    demo = data.get("demographics", {})

    sections = []

    if demo:
        rows = "".join(f"<tr><td>{k}</td><td><strong>{v}</strong></td></tr>" for k, v in demo.items())
        sections.append(f"<h2>Patient Information</h2><table>{rows}</table>")

    insurance = data.get("insurance", {})
    if insurance:
        rows = "".join(f"<tr><td>{k}</td><td><strong>{v}</strong></td></tr>" for k, v in insurance.items())
        sections.append(f"<h2>Insurance</h2><table>{rows}</table>")

    for title, key in [("Medications", "medications"), ("Allergies", "allergies"),
                        ("Medical History", "conditions"), ("Dental", "dental")]:
        items = data.get(key, [])
        if items:
            lis = "".join(f"<li>{i.get('label', i.get('value', ''))}</li>" for i in items)
            sections.append(f"<h2>{title}</h2><ul>{lis}</ul>")

    vitals = data.get("vitals", [])
    if vitals:
        rows = "".join(
            f"<tr><td>{v.get('label','')}</td><td>{v.get('value','')}</td><td>{v.get('date','')}</td></tr>"
            for v in vitals
        )
        sections.append(f"<h2>Recent Vitals</h2><table><tr><th>Measure</th><th>Value</th><th>Date</th></tr>{rows}</table>")

    body = "\n".join(sections)

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Aquifer Health Passport</title>
<style>
  body {{ font-family: -apple-system, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #1a202c; }}
  h1 {{ color: #2b6cb0; border-bottom: 3px solid #2b6cb0; padding-bottom: 8px; }}
  h2 {{ color: #2c5282; margin-top: 24px; font-size: 16px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  td, th {{ padding: 6px 12px; text-align: left; border-bottom: 1px solid #f0f0f0; font-size: 14px; }}
  td:first-child, th:first-child {{ color: #718096; width: 40%; }}
  ul {{ padding-left: 20px; }} li {{ padding: 4px 0; font-size: 14px; }}
  .meta {{ color: #a0aec0; font-size: 12px; margin-top: 32px; border-top: 1px solid #e2e8f0; padding-top: 12px; }}
  .share-key {{ font-family: monospace; font-size: 18px; color: #2b6cb0; font-weight: bold; }}
  @media print {{ body {{ margin: 20px; }} }}
</style></head><body>
<h1>Aquifer Health Passport</h1>
<p>Generated: {data['generated_at'][:10]}<br>
Share Key: <span class="share-key">{data['patient']['share_key']}</span></p>
{body}
<div class="meta">
  <p>This document was generated by Aquifer (aquifer.health).<br>
  Signature: <code>{passport['signature'][:24]}...</code><br>
  To verify, contact the issuing practice or visit aquifer.health/verify.</p>
</div>
</body></html>"""


def verify_passport(passport: dict, signing_key: str) -> bool:
    """Verify a passport's HMAC signature."""
    expected_sig = passport.get("signature", "")
    payload = json.dumps(passport.get("aquifer_health_passport", {}), sort_keys=True)
    computed = hmac.new(
        signing_key.encode(), payload.encode(), hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(expected_sig, computed)


# --- Internal helpers ---

def _extract_demographics(data: dict[str, str]) -> dict:
    mapping = [
        ("NAME", "Name"), ("DATE", "Date of Birth"), ("GENDER", "Gender"),
        ("PHONE", "Phone"), ("EMAIL", "Email"), ("ADDRESS", "Address"),
        ("SSN", "SSN"), ("DOB", "Date of Birth"),
    ]
    result = {}
    for key, label in mapping:
        if data.get(key):
            result[label] = data[key]
    return result


def _extract_insurance(data: dict[str, str]) -> dict:
    mapping = [
        ("ACCOUNT", "Carrier / Account"), ("INSURANCE", "Carrier"),
        ("MEMBER_ID", "Member ID"), ("GROUP", "Group Number"),
    ]
    result = {}
    for key, label in mapping:
        if data.get(key):
            result[label] = data[key]
    return result
