"""Patient portability routes — identity, consent, and cross-practice transfer."""

from __future__ import annotations

import re

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from aquifer.core import PRACTICE_TYPE_DEFAULTS
from aquifer.strata.auth import AuthContext

router = APIRouter(prefix="/patients", tags=["patients"])


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class RegisterPatientRequest(BaseModel):
    email: str
    phone: str | None = None

    @classmethod
    def __get_validators__(cls):
        yield cls._validate

    @classmethod
    def _validate(cls, v):
        return v


class RegisterPatientResponse(BaseModel):
    patient_id: str
    email: str
    share_key: str | None = None
    message: str = "Patient registered. Verify email to enable transfers."


class VerifyPatientRequest(BaseModel):
    patient_id: str
    otp: str


class VerifyPatientResponse(BaseModel):
    verified: bool
    message: str
    share_key: str | None = None


class CreateConsentRequest(BaseModel):
    source_practice_id: str
    target_practice_id: str
    scope: str = "all"  # comma-separated domains, or "all"
    practice_type: str | None = None  # if set, auto-fills scope from PRACTICE_TYPE_DEFAULTS


class ConsentResponse(BaseModel):
    consent_id: str
    patient_id: str
    source_practice_id: str
    target_practice_id: str
    scope: str
    status: str
    authorized_at: str | None
    expires_at: str
    created_at: str


class TransferRequest(BaseModel):
    consent_id: str


class TransferResponse(BaseModel):
    transfer_id: str
    consent_id: str
    token_count: int
    status: str
    created_at: str


class PracticeLink(BaseModel):
    practice_id: str
    source_file_hashes: str | None
    linked_at: str


class PullRequest(BaseModel):
    share_key: str
    practice_type: str | None = None


class PullTransferSummary(BaseModel):
    transfer_id: str
    source_practice_id: str
    token_count: int
    status: str


class PullResponse(BaseModel):
    patient_email_masked: str
    transfers: list[PullTransferSummary]
    total_tokens: int


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def _validate_email(email: str) -> str:
    email = email.lower().strip()
    if not _EMAIL_RE.match(email):
        raise HTTPException(422, "Invalid email address")
    return email


def _require_scope(auth: AuthContext, scope: str) -> None:
    """Ensure the auth context has the required API key scope (JWT always passes)."""
    from aquifer.strata.auth import has_api_key_scopes
    if not has_api_key_scopes(auth, scope):
        raise HTTPException(403, f"API key missing required '{scope}' scope")


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/register", response_model=RegisterPatientResponse, status_code=201)
async def register_patient(body: RegisterPatientRequest, request: Request):
    """Register a new portable patient identity.

    The practice triggers this on behalf of the patient when processing their
    intake form. Returns a patient_id that links to vault tokens.
    """
    auth: AuthContext = request.state.auth
    _require_scope(auth, "deid")

    hub = request.app.state.patient_hub
    email = _validate_email(body.email)

    try:
        identity = hub.register_patient(email, phone=body.phone)
    except ValueError as exc:
        raise HTTPException(409, str(exc))

    request.app.state.db.log_audit(
        practice_id=auth.practice_id,
        action="patient.register",
        resource_type="patient",
        resource_id=identity.patient_id,
        user_id=auth.user_id,
        detail=f"email={email}",
    )

    return RegisterPatientResponse(
        patient_id=identity.patient_id,
        email=identity.email,
        share_key=identity.share_key,
    )


@router.post("/verify", response_model=VerifyPatientResponse)
async def verify_patient(body: VerifyPatientRequest, request: Request):
    """Verify a patient's email address using their one-time password.

    The OTP is generated by the practice calling POST /patients/{id}/otp and
    delivered to the patient out-of-band (Phase B: email delivery).
    """
    auth: AuthContext = request.state.auth
    hub = request.app.state.patient_hub

    if hub.is_otp_rate_limited(body.patient_id):
        raise HTTPException(429, "Too many verification attempts. Please wait before trying again.")

    ok = hub.verify_patient(body.patient_id, body.otp)
    share_key = None
    if ok:
        request.app.state.db.log_audit(
            practice_id=auth.practice_id,
            action="patient.verify",
            resource_type="patient",
            resource_id=body.patient_id,
            user_id=auth.user_id,
        )
        patient = request.app.state.db.get_patient(body.patient_id)
        if patient:
            share_key = patient.get("share_key")

    return VerifyPatientResponse(
        verified=ok,
        message=(
            "Email verified. Save your share key — present it at any Aquifer-connected practice."
            if ok else "Invalid or expired OTP."
        ),
        share_key=share_key,
    )


@router.post("/{patient_id}/otp", status_code=200)
async def generate_otp(patient_id: str, request: Request):
    """Generate and return a new OTP for a patient.

    In Phase A the OTP is returned in the response for the practice to relay.
    When email is configured, the code is sent directly to the patient's email
    and omitted from the response.
    """
    auth: AuthContext = request.state.auth
    _require_scope(auth, "deid")
    hub = request.app.state.patient_hub
    email_config = getattr(request.app.state, "email_config", None)

    try:
        otp, email_sent = hub.generate_otp(patient_id, email_config=email_config)
    except ValueError as exc:
        raise HTTPException(404, str(exc))

    request.app.state.db.log_audit(
        practice_id=auth.practice_id,
        action="patient.otp_generated",
        resource_type="patient",
        resource_id=patient_id,
        user_id=auth.user_id,
    )

    if email_sent:
        return {
            "patient_id": patient_id,
            "message": "Verification code sent to patient's email",
            "ttl_minutes": 15,
        }
    return {"patient_id": patient_id, "otp": otp, "ttl_minutes": 15}


@router.post("/{patient_id}/link", status_code=204)
async def link_patient_to_practice(patient_id: str, request: Request):
    """Associate a patient with the authenticated practice.

    Body: { "source_file_hashes": "hash1,hash2,..." } (optional)
    Called by the de-identification pipeline after processing a patient file.
    """
    auth: AuthContext = request.state.auth
    _require_scope(auth, "deid")
    hub = request.app.state.patient_hub

    body = await request.json() if request.headers.get("content-type", "").startswith("application/json") else {}
    source_file_hashes = body.get("source_file_hashes", "") if isinstance(body, dict) else ""

    try:
        hub.link_patient_to_practice(patient_id, auth.practice_id, source_file_hashes)
    except ValueError as exc:
        raise HTTPException(404, str(exc))


@router.post("/{patient_id}/consent", response_model=ConsentResponse, status_code=201)
async def create_consent(patient_id: str, body: CreateConsentRequest, request: Request):
    """Create a consent record authorizing data sharing from source to target practice.

    The practice creates this on behalf of the patient. Status starts as 'pending'.
    Use POST /patients/{id}/consent/{consent_id}/authorize to activate it.
    """
    auth: AuthContext = request.state.auth
    hub = request.app.state.patient_hub

    # Resolve scope from practice_type defaults when no explicit scope was set
    scope = body.scope
    if body.practice_type is not None and scope == "all":
        defaults = PRACTICE_TYPE_DEFAULTS.get(body.practice_type.lower())
        if defaults is not None:
            scope = ",".join(sorted(str(d.value) for d in defaults))

    try:
        consent = hub.create_consent(
            patient_id=patient_id,
            source_practice_id=body.source_practice_id,
            target_practice_id=body.target_practice_id,
            scope=scope,
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc))

    request.app.state.db.log_audit(
        practice_id=auth.practice_id,
        action="consent.created",
        resource_type="consent",
        resource_id=consent.consent_id,
        user_id=auth.user_id,
        detail=(
            f"patient={patient_id} source={body.source_practice_id} "
            f"target={body.target_practice_id} scope={scope}"
            + (f" practice_type={body.practice_type}" if body.practice_type else "")
        ),
    )
    return ConsentResponse(**consent.model_dump())


@router.post("/{patient_id}/consent/{consent_id}/authorize", response_model=ConsentResponse)
async def authorize_consent(patient_id: str, consent_id: str, request: Request):
    """Authorize a pending consent, enabling data transfer."""
    auth: AuthContext = request.state.auth
    hub = request.app.state.patient_hub

    try:
        consent = hub.authorize_consent(consent_id, patient_id)
    except ValueError as exc:
        raise HTTPException(400, str(exc))

    request.app.state.db.log_audit(
        practice_id=auth.practice_id,
        action="consent.authorized",
        resource_type="consent",
        resource_id=consent_id,
        user_id=auth.user_id,
        detail=f"patient={patient_id}",
    )
    return ConsentResponse(**consent.model_dump())


@router.delete("/{patient_id}/consent/{consent_id}", status_code=204)
async def revoke_consent(patient_id: str, consent_id: str, request: Request):
    """Revoke a consent. Patients can always revoke, regardless of current status."""
    auth: AuthContext = request.state.auth
    hub = request.app.state.patient_hub

    ok = hub.revoke_consent(consent_id, patient_id)
    if not ok:
        raise HTTPException(404, "Consent not found or does not belong to this patient")

    request.app.state.db.log_audit(
        practice_id=auth.practice_id,
        action="consent.revoked",
        resource_type="consent",
        resource_id=consent_id,
        user_id=auth.user_id,
        detail=f"patient={patient_id}",
    )


@router.post("/{patient_id}/transfer", response_model=TransferResponse, status_code=201)
async def execute_transfer(patient_id: str, body: TransferRequest, request: Request):
    """Execute a vault-to-vault PHI transfer under an authorized consent.

    The target practice triggers this after the patient has authorized consent.
    PHI is re-encrypted server-side — never exposed in plaintext on the wire.
    """
    auth: AuthContext = request.state.auth
    hub = request.app.state.patient_hub

    # Verify the consent belongs to this patient
    db = request.app.state.db
    consent = db.get_consent(body.consent_id)
    if not consent:
        raise HTTPException(404, "Consent not found")
    if consent["patient_id"] != patient_id:
        raise HTTPException(404, "Consent not found")
    # Require the calling practice to be the target (they receive the data)
    if consent["target_practice_id"] != auth.practice_id:
        raise HTTPException(
            403, "Only the target practice can trigger a transfer"
        )

    try:
        record = hub.execute_transfer(body.consent_id)
    except ValueError as exc:
        raise HTTPException(400, str(exc))

    return TransferResponse(**record.model_dump())


@router.get("/{patient_id}/practices", response_model=list[PracticeLink])
async def list_patient_practices(patient_id: str, request: Request):
    """List all practices the patient is linked to."""
    db = request.app.state.db

    # Verify patient exists
    patient = db.get_patient(patient_id)
    if not patient:
        raise HTTPException(404, "Patient not found")

    links = db.get_patient_practices(patient_id)
    return [
        PracticeLink(
            practice_id=link["practice_id"],
            source_file_hashes=link.get("source_file_hashes"),
            linked_at=str(link["linked_at"]),
        )
        for link in links
    ]


@router.get("/{patient_id}/consents", response_model=list[ConsentResponse])
async def list_patient_consents(patient_id: str, request: Request):
    """List all consent records for a patient."""
    db = request.app.state.db

    patient = db.get_patient(patient_id)
    if not patient:
        raise HTTPException(404, "Patient not found")

    rows = db.list_consents_for_patient(patient_id)
    return [
        ConsentResponse(
            consent_id=r["id"],
            patient_id=r["patient_id"],
            source_practice_id=r["source_practice_id"],
            target_practice_id=r["target_practice_id"],
            scope=r["scope"],
            status=r["status"],
            authorized_at=str(r["authorized_at"]) if r.get("authorized_at") else None,
            expires_at=str(r["expires_at"]),
            created_at=str(r["created_at"]),
        )
        for r in rows
    ]


@router.post("/pull", response_model=PullResponse, status_code=200)
async def pull_records(body: PullRequest, request: Request):
    """Instant record pull using a patient share key.

    Practice B sends the share key the patient presents at check-in.
    Aquifer fetches all records from every practice the patient has been to,
    re-encrypts them into Practice B's vault, and returns a summary.

    The share key IS the authorization — presenting it constitutes consent.
    """
    auth: AuthContext = request.state.auth
    hub = request.app.state.patient_hub
    db = request.app.state.db

    # Normalize the key so "aq-xxxx-xxxx" or "AQXXXXXXXX" all work
    share_key = body.share_key.strip().upper()
    if not share_key.startswith("AQ-"):
        raise HTTPException(422, "Share key must be in AQ-XXXX-XXXX format")

    patient = db.get_patient_by_share_key(share_key)
    if not patient:
        raise HTTPException(404, "Share key not found")

    try:
        transfers = hub.pull_records(
            share_key=share_key,
            target_practice_id=auth.practice_id,
            target_practice_type=body.practice_type,
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc))

    db.log_audit(
        practice_id=auth.practice_id,
        action="patient.pull_records",
        resource_type="patient",
        resource_id=patient["id"],
        user_id=auth.user_id,
        detail=f"share_key={share_key} practice_type={body.practice_type} transfers={len(transfers)}",
    )

    email = patient["email"]
    at = email.index("@")
    masked = email[:2] + ("*" * (at - 2)) + email[at:]

    summaries = []
    for t in transfers:
        consent = db.get_consent(t.consent_id)
        source_id = consent["source_practice_id"] if consent else t.consent_id
        summaries.append(PullTransferSummary(
            transfer_id=t.transfer_id,
            source_practice_id=source_id,
            token_count=t.token_count,
            status=t.status,
        ))

    return PullResponse(
        patient_email_masked=masked,
        transfers=summaries,
        total_tokens=sum(t.token_count for t in transfers),
    )
